// ─────────────────────────────────────────────────────────────────────────────
// Blink Browser Experience
//
// A scrollable content reader controlled by eye blinks detected from
// frontal EEG channels. Includes a built-in calibration wizard that
// adapts to each user's blink amplitude and persists the profile.
//
// Scroll modes:
//  • Reader mode — built-in articles with smooth blink-scrolling
//  • Web mode — iframe with URL bar + transform-based scrolling
//
// Controls:
//  • Blink → scroll in current direction
//  • Space / click direction button → toggle up/down
//  • +/− → adjust scroll amount
//  • S → toggle settings
//  • Esc → exit
// ─────────────────────────────────────────────────────────────────────────────

import { useState, useEffect, useRef, useCallback } from "react";
import type { EEGData } from "../../types";
import {
  type BlinkCalibration,
  type CalibrationError,
  type TimedReading,
  loadCalibration,
  saveCalibration,
  readAmplitude,
  findPeaks,
  computeCalibration,
  isCalibration,
  checkSignalQuality,
  type SignalQuality,
} from "./blinkDetect";

// ═════════════════════════════════════════════════════════════════════════════
// Built-in articles for reader mode
// ═════════════════════════════════════════════════════════════════════════════

const ARTICLES = [
  {
    title: "Understanding Brain-Computer Interfaces",
    body: `Brain-computer interfaces (BCIs) represent one of the most exciting frontiers in neuroscience and engineering. These systems create a direct communication pathway between the brain and an external device, bypassing traditional neuromuscular output channels.

The concept of BCIs dates back to the 1970s, when Jacques Vidal at UCLA first coined the term and demonstrated that electrical signals from the brain could be used to control a cursor on a computer screen. Since then, the field has grown exponentially, with applications ranging from medical rehabilitation to entertainment.

How BCIs Work

At their core, BCIs rely on detecting and interpreting neural signals. The most common non-invasive approach uses electroencephalography (EEG) — the same technology powering this very experience you're using right now. EEG electrodes placed on the scalp detect the tiny electrical potentials generated by populations of neurons firing in synchrony.

These signals are incredibly weak — typically measured in microvolts (µV), which is one-millionth of a volt. For comparison, a standard AA battery produces 1.5 volts, which is about 1.5 million times stronger than a typical EEG signal. Despite this, modern amplifiers and signal processing techniques can reliably extract meaningful information from these faint neural whispers.

Types of Brain Signals Used in BCIs

Several types of brain signals have proven useful for BCI applications:

1. Event-Related Potentials (ERPs): These are stereotyped responses to specific stimuli. The P300 wave, a positive deflection occurring about 300 milliseconds after a rare or meaningful stimulus, has been widely used in spelling systems where users can select letters by focusing on them.

2. Steady-State Visual Evoked Potentials (SSVEPs): When looking at a flickering light, the visual cortex generates oscillations at the same frequency. By presenting multiple stimuli flickering at different frequencies, a BCI can determine which one the user is attending to.

3. Sensorimotor Rhythms (SMRs): Imagining movement of different body parts produces characteristic changes in the mu (8-12 Hz) and beta (13-30 Hz) rhythms over the motor cortex. This is the basis for motor imagery BCIs.

4. Blink and Eye Movement Artifacts: While traditionally considered noise in EEG research, eye blinks and movements produce large, easily detectable signals — exactly what this Blink Browser experience leverages. Blinks generate deflections of 100-500 µV on frontal electrodes, making them one of the most reliable BCI control signals.

The Future of BCIs

Current research is pushing the boundaries of what's possible with BCIs. Companies like Neuralink are developing high-density implantable arrays that could decode complex thoughts and intentions. Meanwhile, non-invasive approaches continue to improve, with dry electrodes, machine learning algorithms, and real-time processing making BCIs more accessible than ever.

The convergence of neuroscience, artificial intelligence, and miniaturized electronics suggests a future where brain-computer interfaces become as commonplace as touchscreens are today. Projects like PiEEG are already democratizing access to this technology, putting affordable, open-source EEG hardware in the hands of makers, researchers, and enthusiasts worldwide.`,
  },
  {
    title: "The Science of Eye Blinks",
    body: `You blink about 15-20 times per minute — roughly 1,200 times per hour, and up to 28,800 times per day. Yet you rarely notice it. This seemingly trivial reflex is actually a complex neurological event with fascinating properties that make it ideal for brain-computer interface control.

Anatomy of a Blink

A blink involves the rapid closing and opening of the eyelid, primarily driven by the orbicularis oculi muscle (for closing) and the levator palpebrae superioris muscle (for opening). A complete blink cycle takes about 300-400 milliseconds, with the closing phase being faster (roughly 80ms) than the opening phase (roughly 170ms).

Why Blinks Show Up in EEG

When you blink, the movement of the eyelid across the cornea creates a measurable electrical potential change. The eye acts like a small battery, with the cornea being positively charged relative to the retina. This corneoretinal dipole means that any eye movement — including blinks — generates electrical fields that propagate across the scalp and are easily picked up by frontal EEG electrodes.

This is why EEG researchers traditionally viewed blinks as artifacts to be removed. But from a BCI perspective, this strong, reliable signal is a feature, not a bug. Blink artifacts typically range from 100 to 500 µV peak-to-peak on frontal channels (Fp1, Fp2), compared to normal EEG activity of 10-100 µV. This excellent signal-to-noise ratio makes blink detection one of the most robust BCI control methods available.

Types of Blinks

Not all blinks are created equal:

Spontaneous Blinks: These occur naturally to keep the cornea moist and happen reflexively without conscious thought. They're typically smaller in amplitude and occur at semi-regular intervals.

Voluntary Blinks: Deliberate, intentional blinks tend to be stronger and more forceful. They produce larger EEG deflections and are easier to detect — perfect for BCI control.

Reflex Blinks: Triggered by sudden stimuli (bright light, loud sound, approaching object), these are the fastest but least useful for intentional control.

Blink Rate and Cognitive State

Interestingly, blink rate varies with cognitive state. During focused reading, blink rate drops to about 3-4 per minute. During conversation, it increases to about 26 per minute. Fatigue and drowsiness also increase blink rate and duration. This means a blink-based BCI could potentially adapt its behavior based on the user's cognitive state.

Blink Detection in This Experience

The Blink Browser uses a straightforward but effective detection algorithm:

1. Continuous monitoring of frontal EEG channels (Fp1 and Fp2)
2. Computing peak-to-peak amplitude in a sliding 100ms window
3. Comparing against a personalized threshold set during calibration
4. Applying a refractory period to prevent double-counting
5. Validating blink duration (too short = noise, too long = sustained artifact)

The calibration process is crucial because blink amplitude varies significantly between individuals, depending on factors like skin impedance, electrode placement, muscle strength, and even facial anatomy. By calibrating specifically for each user, the system achieves high detection accuracy with minimal false positives.

Practical Applications

Beyond scrolling through content, blink-based BCIs have been used for:

• Communication systems for patients with locked-in syndrome
• Fatigue detection in drivers and pilots  
• Hands-free device control in sterile environments (operating rooms)
• Gaming interfaces
• Accessibility tools for people with motor impairments

The simplicity and reliability of blink detection makes it an excellent entry point into the world of brain-computer interfaces.`,
  },
  {
    title: "EEG Frequency Bands: A Guide",
    body: `The brain is always electrically active, producing oscillations across a wide range of frequencies. These oscillations are not random — they reflect the coordinated activity of neural populations and are associated with specific cognitive states and functions.

Delta Waves (0.5-4 Hz)

Delta waves are the slowest brain oscillations and have the highest amplitude. They are most prominent during deep, dreamless sleep (stages 3 and 4 of non-REM sleep) and are thought to play a role in memory consolidation and brain restoration.

In waking adults, delta activity is normally minimal. Excessive delta during wakefulness can indicate brain injury, encephalopathy, or certain neurological conditions. However, some research suggests that frontal delta activity may also be involved in attention and motivation.

Theta Waves (4-8 Hz)

Theta oscillations are associated with drowsiness, light sleep, and the transition between waking and sleeping (the hypnagogic state). In this twilight zone of consciousness, many people experience vivid imagery and creative insights.

During waking, frontal theta increases during working memory tasks, error processing, and emotional regulation. The famous "theta burst" seen during meditation has been linked to enhanced creativity and insight. Hippocampal theta is also crucial for spatial navigation and memory encoding.

Alpha Waves (8-13 Hz)

Perhaps the most well-known brain rhythm, alpha waves were the first to be identified by Hans Berger in 1929 when he invented the electroencephalogram. Alpha is most prominent over posterior (occipital) regions when the eyes are closed and the mind is relaxed but alert.

The classic demonstration: close your eyes, relax, and alpha power increases dramatically. Open your eyes or start thinking about a math problem, and alpha is suppressed (this is called alpha blocking or alpha desynchronization).

Alpha is thought to play an inhibitory role, helping to suppress processing in brain regions that are not relevant to the current task. This "gating" function makes alpha a key target for neurofeedback training, where users learn to voluntarily control their alpha levels.

Beta Waves (13-30 Hz)

Beta oscillations are associated with active thinking, problem-solving, and focused concentration. They are most prominent over frontal and central regions during cognitive tasks.

Low beta (13-15 Hz, sometimes called SMR or sensorimotor rhythm) is associated with calm, focused attention. Mid-beta (15-20 Hz) reflects active engagement. High beta (20-30 Hz) can indicate anxiety, stress, or intense cognitive processing.

In motor cortex, beta power decreases before and during movement (event-related desynchronization) and increases after movement completion (event-related synchronization or beta rebound). Motor imagery BCIs exploit these changes to decode intended movements.

Gamma Waves (30-100 Hz)

Gamma oscillations are the fastest brain rhythms routinely studied in EEG. They are associated with higher cognitive functions including perception, attention, consciousness, and the binding of information from different brain regions into coherent percepts.

When you recognize a face, understand a sentence, or have an "aha!" moment, gamma activity typically increases. Some researchers believe gamma oscillations are the neural correlate of consciousness itself, though this remains debated.

Detecting gamma in scalp EEG is challenging because the signals are small and easily contaminated by muscle artifact (EMG), which also contains high-frequency energy. This is why careful artifact rejection is essential for gamma research.

Practical Implications for BCI

Each frequency band offers different possibilities for BCI control:

• Alpha: Can be voluntarily modulated with practice (neurofeedback), enabling eyes-open/closed control schemes
• Beta/SMR: Motor imagery BCIs use beta changes to decode intended movements
• Theta: Could detect attentional states and adapt BCI behavior
• Gamma: Too variable for direct control but useful for cognitive state monitoring

The PiEEG system you're using detects all these bands in real-time. Explore the FFT panel in the main dashboard to see your own brain's frequency spectrum in action!

Understanding Your Own Brain Rhythms

Everyone's brain produces a unique pattern of oscillations. Factors that influence your EEG include:

• Genetics: Twin studies show EEG patterns are highly heritable
• Age: Alpha frequency increases during childhood and may slow in aging
• Cognitive style: Visual thinkers may show different alpha patterns than verbal thinkers  
• Meditation practice: Regular meditators often show enhanced alpha and theta
• Caffeine, sleep, stress: All significantly affect frequency band power

By watching your own EEG in real-time with PiEEG, you can begin to understand the relationship between your mental state and your brain's electrical activity — the first step toward effective brain-computer interface control.`,
  },
];

// ═════════════════════════════════════════════════════════════════════════════
// Styles (Geist design language)
// ═════════════════════════════════════════════════════════════════════════════

const S = {
  // ── Full-screen container ──
  root: {
    position: "fixed" as const,
    inset: 0,
    background: "#000",
    color: "#ededed",
    fontFamily: "'Geist','Inter',-apple-system,BlinkMacSystemFont,system-ui,sans-serif",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    zIndex: 9000,
  },

  // ── Calibration wizard ──
  wizardWrap: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  wizardCard: {
    background: "#111",
    border: "1px solid rgba(255,255,255,0.06)",
    borderRadius: 16,
    padding: 40,
    maxWidth: 520,
    width: "100%",
    textAlign: "center" as const,
  },
  wizardTitle: {
    fontSize: 22,
    fontWeight: 600,
    marginBottom: 8,
  },
  wizardSub: {
    color: "#a1a1a1",
    fontSize: 14,
    lineHeight: 1.6,
    marginBottom: 24,
  },
  wizardStep: {
    fontSize: 12,
    color: "#666",
    textTransform: "uppercase" as const,
    letterSpacing: 1,
    marginBottom: 16,
  },
  progressBar: {
    width: "100%",
    height: 6,
    background: "#222",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 20,
  },
  progressFill: {
    height: "100%",
    background: "#0070f3",
    borderRadius: 3,
    transition: "width 0.3s",
  },
  blinkDot: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    margin: "24px auto",
    transition: "all 0.15s",
  },
  ampMeter: {
    height: 4,
    background: "#222",
    borderRadius: 2,
    overflow: "hidden",
    marginTop: 12,
    marginBottom: 8,
  },
  ampFill: {
    height: "100%",
    borderRadius: 2,
    transition: "width 0.05s",
  },
  resultGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    margin: "20px 0",
    textAlign: "left" as const,
  },
  resultItem: {
    background: "#0a0a0a",
    borderRadius: 8,
    padding: "12px 16px",
  },
  resultLabel: {
    fontSize: 11,
    color: "#666",
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
  },
  resultValue: {
    fontSize: 20,
    fontWeight: 600,
    fontFamily: "'Geist Mono',monospace",
    marginTop: 4,
  },

  // ── Buttons ──
  btn: {
    padding: "10px 20px",
    borderRadius: 8,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "#171717",
    color: "#ededed",
    fontSize: 14,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "background 0.15s",
  },
  btnPrimary: {
    padding: "10px 24px",
    borderRadius: 8,
    border: "none",
    background: "#0070f3",
    color: "#fff",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "background 0.15s",
  },
  btnSmall: {
    padding: "6px 12px",
    borderRadius: 6,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "#111",
    color: "#a1a1a1",
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  btnRow: {
    display: "flex",
    gap: 12,
    justifyContent: "center",
    marginTop: 20,
  },

  // ── Browse mode ──
  header: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 16px",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    flexShrink: 0,
    background: "#0a0a0a",
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
  },
  meterWrap: {
    flex: 1,
    maxWidth: 200,
    height: 20,
    background: "#111",
    borderRadius: 4,
    overflow: "hidden",
    position: "relative" as const,
    border: "1px solid rgba(255,255,255,0.06)",
  },
  meterFill: {
    height: "100%",
    transition: "width 0.05s, background 0.15s",
    borderRadius: 3,
  },
  meterThreshLine: {
    position: "absolute" as const,
    top: 0,
    bottom: 0,
    width: 2,
    background: "#f59e0b",
    opacity: 0.8,
  },
  blinkBadge: {
    padding: "4px 10px",
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
    fontFamily: "'Geist Mono',monospace",
    transition: "all 0.1s",
  },
  dirBtn: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    padding: "4px 12px",
    borderRadius: 6,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "#111",
    color: "#ededed",
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  urlBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 16px",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    background: "#0a0a0a",
    flexShrink: 0,
  },
  urlInput: {
    flex: 1,
    padding: "6px 12px",
    borderRadius: 6,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "#111",
    color: "#ededed",
    fontSize: 13,
    fontFamily: "'Geist Mono',monospace",
    outline: "none",
  },
  modeTab: {
    padding: "4px 10px",
    borderRadius: 6,
    border: "1px solid rgba(255,255,255,0.08)",
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
  content: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "32px 24px",
    scrollBehavior: "smooth" as const,
  },
  article: {
    maxWidth: 680,
    margin: "0 auto 48px",
  },
  articleTitle: {
    fontSize: 28,
    fontWeight: 700,
    marginBottom: 16,
    lineHeight: 1.3,
  },
  articleBody: {
    fontSize: 16,
    lineHeight: 1.8,
    color: "#ccc",
    whiteSpace: "pre-wrap" as const,
  },
  articleDivider: {
    border: "none",
    borderTop: "1px solid rgba(255,255,255,0.06)",
    margin: "48px auto",
    maxWidth: 200,
  },
  iframeWrap: {
    flex: 1,
    overflow: "hidden",
    position: "relative" as const,
  },
  iframe: {
    width: "100%",
    height: "300vh",
    border: "none",
    pointerEvents: "none" as const,
    transition: "transform 0.3s ease-out",
  },
  settingsPanel: {
    position: "absolute" as const,
    bottom: 0,
    left: 0,
    right: 0,
    background: "#111",
    borderTop: "1px solid rgba(255,255,255,0.08)",
    padding: "16px 24px",
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 16,
    alignItems: "center",
    zIndex: 10,
  },
  settLabel: {
    fontSize: 12,
    color: "#666",
    marginBottom: 4,
  },
  settValue: {
    fontSize: 14,
    fontFamily: "'Geist Mono',monospace",
  },
  footer: {
    padding: "6px 16px",
    borderTop: "1px solid rgba(255,255,255,0.06)",
    background: "#0a0a0a",
    display: "flex",
    alignItems: "center",
    gap: 16,
    fontSize: 12,
    color: "#666",
    flexShrink: 0,
  },
};

// ═════════════════════════════════════════════════════════════════════════════
// Calibration Wizard
// ═════════════════════════════════════════════════════════════════════════════

type CalStep = "intro" | "signal-check" | "baseline" | "blink" | "done" | "error";

interface CalibrationWizardProps {
  eegData: EEGData;
  existing: BlinkCalibration | null;
  onComplete: (cal: BlinkCalibration) => void;
  onSkip?: () => void;
  onExit: () => void;
}

function CalibrationWizard({
  eegData,
  existing,
  onComplete,
  onSkip,
  onExit,
}: CalibrationWizardProps) {
  const [step, setStep] = useState<CalStep>("intro");
  const [progress, setProgress] = useState(0);
  const [detectedBlinks, setDetectedBlinks] = useState(0);
  const [amp, setAmp] = useState(0);
  const [result, setResult] = useState<BlinkCalibration | null>(null);
  const [errorMsg, setErrorMsg] = useState("");
  const [signalInfo, setSignalInfo] = useState<
    { ch: number; quality: SignalQuality; p2p: number }[]
  >([]);
  const [blinkPromptActive, setBlinkPromptActive] = useState(false);

  const baselineRef = useRef<number[]>([]);
  const blinkRef = useRef<TimedReading[]>([]);
  const channels = [0, 1]; // Fp1, Fp2

  // ── Signal quality check (1.5 seconds) ──
  useEffect(() => {
    if (step !== "signal-check") return;
    const start = performance.now();
    const dur = 1500;

    const iv = setInterval(() => {
      const elapsed = performance.now() - start;
      setProgress(Math.min(1, elapsed / dur));

      const a = readAmplitude(eegData, channels);
      setAmp(a);

      if (elapsed >= dur) {
        clearInterval(iv);
        const { perChannel } = checkSignalQuality(eegData, channels);
        setSignalInfo(perChannel);

        const anyGood = perChannel.some((c) => c.quality === "good");
        const anyFlat = perChannel.every((c) => c.quality === "flat");

        if (anyFlat) {
          setErrorMsg(
            "No signal detected on Fp1 or Fp2. Check that electrodes are " +
              "connected and have good skin contact.",
          );
          setStep("error");
        } else if (!anyGood) {
          // Weak/noisy but not flat — warn but allow proceeding
          setErrorMsg(
            "Signal quality is poor on both Fp channels. " +
              "Calibration may still work, but results will be better with " +
              "improved electrode contact.",
          );
          setStep("error");
        } else {
          setStep("baseline");
          setProgress(0);
        }
      }
    }, 100);

    return () => clearInterval(iv);
  }, [step, eegData]);

  // ── Baseline collection (4 seconds, with outlier-robust collection) ──
  useEffect(() => {
    if (step !== "baseline") return;
    baselineRef.current = [];
    const start = performance.now();
    const dur = 4000;

    const iv = setInterval(() => {
      const a = readAmplitude(eegData, channels);
      baselineRef.current.push(a);
      setAmp(a);
      const elapsed = performance.now() - start;
      setProgress(Math.min(1, elapsed / dur));
      if (elapsed >= dur) {
        clearInterval(iv);
        setStep("blink");
        setProgress(0);
        setDetectedBlinks(0);
      }
    }, 80); // ~50 readings over 4s

    return () => clearInterval(iv);
  }, [step, eegData]);

  // ── Blink collection (~15 seconds, 5 prompts with real-time detection) ──
  useEffect(() => {
    if (step !== "blink") return;
    blinkRef.current = [];
    const start = performance.now();
    const dur = 15000;
    const promptInterval = 2800;
    const promptDuration = 1200; // green dot visible for 1.2s
    let nextPromptOn = start + 800;
    let nextPromptOff = nextPromptOn + promptDuration;
    let promptsShown = 0;

    // Live blink detection during calibration for feedback
    // Use a simple threshold from baseline so far
    let lastBlinkTime = 0;
    const REFRACTORY = 400;

    const iv = setInterval(() => {
      const now = performance.now();
      const a = readAmplitude(eegData, channels);
      blinkRef.current.push({ time: now, amp: a });
      setAmp(a);

      // Prompt timing
      if (now >= nextPromptOn && promptsShown < 5) {
        if (!blinkPromptActive) setBlinkPromptActive(true);
      }
      if (now >= nextPromptOff && blinkPromptActive) {
        setBlinkPromptActive(false);
        promptsShown++;
        nextPromptOn = now + (promptInterval - promptDuration);
        nextPromptOff = nextPromptOn + promptDuration;
      }

      // Live blink count: use a rough threshold from baseline
      // (just for UI feedback — real calibration uses computeCalibration)
      if (baselineRef.current.length > 10) {
        const blSorted = [...baselineRef.current].sort((a, b) => a - b);
        const p80 = blSorted[Math.floor(blSorted.length * 0.8)];
        const roughThresh = Math.max(p80 * 2, 60);
        if (a > roughThresh && now - lastBlinkTime > REFRACTORY) {
          lastBlinkTime = now;
          setDetectedBlinks((c) => c + 1);
        }
      }

      const elapsed = now - start;
      setProgress(Math.min(1, elapsed / dur));

      if (elapsed >= dur) {
        clearInterval(iv);
        setBlinkPromptActive(false);
        const cal = computeCalibration(
          baselineRef.current,
          blinkRef.current,
          channels,
        );
        if (isCalibration(cal)) {
          setResult(cal);
          setStep("done");
        } else {
          setErrorMsg((cal as CalibrationError).message);
          setStep("error");
        }
      }
    }, 40); // 25 Hz polling

    return () => {
      clearInterval(iv);
      setBlinkPromptActive(false);
    };
  }, [step, eegData]);

  // ── Keyboard: Esc to exit ──
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") onExit();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onExit]);

  // ── Amplitude display scale ──
  const ampPct = Math.min(100, (amp / 400) * 100);
  const ampColor = amp > 150 ? "#00c853" : amp > 80 ? "#eab308" : "#333";

  const qualityColor = (q: SignalQuality) =>
    q === "good" ? "#00c853" : q === "weak" ? "#eab308" : q === "noisy" ? "#f85149" : "#666";
  const qualityLabel = (q: SignalQuality) =>
    q === "good" ? "Good" : q === "weak" ? "Weak" : q === "noisy" ? "Noisy" : "No signal";

  return (
    <div style={S.root}>
      <div style={S.wizardWrap}>
        <div style={S.wizardCard}>
          {/* ── INTRO ── */}
          {step === "intro" && (
            <>
              <div style={{ fontSize: 40, marginBottom: 12 }}>👁️</div>
              <h2 style={S.wizardTitle}>Blink Calibration</h2>
              <p style={S.wizardSub}>
                This calibration measures your baseline brain activity and blink
                amplitude to create a personalized detection profile.
                <br />
                <br />
                You'll need about 20 seconds. Make sure electrodes on{" "}
                <strong>Fp1</strong> and <strong>Fp2</strong> (channels 0 &amp;
                1) have good contact.
              </p>
              <div style={S.btnRow}>
                <button style={S.btn} onClick={onExit}>
                  ← Exit
                </button>
                {onSkip && (
                  <button style={S.btn} onClick={onSkip}>
                    Skip
                  </button>
                )}
                <button
                  style={S.btnPrimary}
                  onClick={() => {
                    setStep("signal-check");
                    setProgress(0);
                  }}
                >
                  Start Calibration
                </button>
              </div>
            </>
          )}

          {/* ── SIGNAL CHECK ── */}
          {step === "signal-check" && (
            <>
              <div style={S.wizardStep}>Checking signal…</div>
              <h2 style={S.wizardTitle}>Verifying electrode contact</h2>
              <p style={S.wizardSub}>
                Checking Fp1 and Fp2 signal quality…
              </p>
              <div style={S.progressBar}>
                <div
                  style={{
                    ...S.progressFill,
                    width: `${progress * 100}%`,
                  }}
                />
              </div>
              <div style={S.ampMeter}>
                <div
                  style={{
                    ...S.ampFill,
                    width: `${ampPct}%`,
                    background: ampColor,
                  }}
                />
              </div>
            </>
          )}

          {/* ── BASELINE ── */}
          {step === "baseline" && (
            <>
              <div style={S.wizardStep}>Step 1 of 2 — Baseline</div>
              <h2 style={S.wizardTitle}>Relax, eyes open</h2>
              <p style={S.wizardSub}>
                Look at the screen and relax. Try to minimize blinking.
                <br />
                <span style={{ fontSize: 12, color: "#555" }}>
                  (It's OK if you blink a few times — the algorithm handles it.)
                </span>
              </p>
              {signalInfo.length > 0 && (
                <div style={{ display: "flex", justifyContent: "center", gap: 16, marginBottom: 12 }}>
                  {signalInfo.map((s) => (
                    <div key={s.ch} style={{ fontSize: 12 }}>
                      <span style={{ color: "#666" }}>Ch{s.ch}: </span>
                      <span style={{ color: qualityColor(s.quality), fontWeight: 600 }}>
                        {qualityLabel(s.quality)}
                      </span>
                    </div>
                  ))}
                </div>
              )}
              <div style={S.progressBar}>
                <div
                  style={{
                    ...S.progressFill,
                    width: `${progress * 100}%`,
                  }}
                />
              </div>
              <div style={S.ampMeter}>
                <div
                  style={{
                    ...S.ampFill,
                    width: `${ampPct}%`,
                    background: ampColor,
                  }}
                />
              </div>
              <div style={{ fontSize: 12, color: "#666" }}>
                {(progress * 4).toFixed(1)}s / 4.0s
              </div>
            </>
          )}

          {/* ── BLINK ── */}
          {step === "blink" && (
            <>
              <div style={S.wizardStep}>Step 2 of 2 — Blink Detection</div>
              <h2 style={S.wizardTitle}>Blink when you see the green dot</h2>
              <p style={S.wizardSub}>
                Blink clearly and deliberately each time the dot turns green.
              </p>
              <div
                style={{
                  ...S.blinkDot,
                  background: blinkPromptActive ? "#00c853" : "#222",
                  boxShadow: blinkPromptActive
                    ? "0 0 30px rgba(0,200,83,0.4)"
                    : "none",
                }}
              />
              <div style={{ fontSize: 14, fontFamily: "'Geist Mono',monospace" }}>
                {detectedBlinks > 0 ? (
                  <span style={{ color: "#00c853" }}>
                    {detectedBlinks} blink{detectedBlinks !== 1 ? "s" : ""} detected
                  </span>
                ) : (
                  <span style={{ color: "#666" }}>Waiting for blinks…</span>
                )}
              </div>
              <div style={{ ...S.progressBar, marginTop: 16 }}>
                <div
                  style={{
                    ...S.progressFill,
                    width: `${progress * 100}%`,
                    background: "#00c853",
                  }}
                />
              </div>
              <div style={S.ampMeter}>
                <div
                  style={{
                    ...S.ampFill,
                    width: `${ampPct}%`,
                    background: ampColor,
                  }}
                />
              </div>
            </>
          )}

          {/* ── DONE ── */}
          {step === "done" && result && (
            <>
              <div style={{ fontSize: 40, marginBottom: 12 }}>✅</div>
              <h2 style={S.wizardTitle}>Calibration Complete</h2>
              <p style={S.wizardSub}>
                Your blink profile has been computed. These settings will be
                saved for future sessions.
              </p>
              <div style={S.resultGrid}>
                <div style={S.resultItem}>
                  <div style={S.resultLabel}>Baseline</div>
                  <div style={S.resultValue}>
                    {result.baselineCeiling.toFixed(0)} µV
                  </div>
                </div>
                <div style={S.resultItem}>
                  <div style={S.resultLabel}>Blink median</div>
                  <div style={S.resultValue}>
                    {result.blinkMedian.toFixed(0)} µV
                  </div>
                </div>
                <div style={S.resultItem}>
                  <div style={S.resultLabel}>Threshold</div>
                  <div style={{ ...S.resultValue, color: "#f59e0b" }}>
                    {result.threshold.toFixed(0)} µV
                  </div>
                </div>
                <div style={S.resultItem}>
                  <div style={S.resultLabel}>SNR</div>
                  <div style={{
                    ...S.resultValue,
                    color: result.snr > 3 ? "#00c853" : result.snr > 2 ? "#eab308" : "#f85149",
                  }}>
                    {result.snr.toFixed(1)}×
                  </div>
                </div>
              </div>
              <div style={S.btnRow}>
                <button
                  style={S.btn}
                  onClick={() => {
                    setStep("intro");
                    setProgress(0);
                    setResult(null);
                    setDetectedBlinks(0);
                  }}
                >
                  Redo
                </button>
                <button
                  style={S.btnPrimary}
                  onClick={() => onComplete(result)}
                >
                  Start Browsing →
                </button>
              </div>
            </>
          )}

          {/* ── ERROR ── */}
          {step === "error" && (
            <>
              <div style={{ fontSize: 40, marginBottom: 12 }}>⚠️</div>
              <h2 style={S.wizardTitle}>Calibration Issue</h2>
              <p style={S.wizardSub}>{errorMsg}</p>
              {signalInfo.length > 0 && (
                <div style={{ display: "flex", justifyContent: "center", gap: 16, marginBottom: 16 }}>
                  {signalInfo.map((s) => (
                    <div key={s.ch} style={{ fontSize: 12 }}>
                      <span style={{ color: "#666" }}>Ch{s.ch}: </span>
                      <span style={{ color: qualityColor(s.quality), fontWeight: 600 }}>
                        {qualityLabel(s.quality)} ({s.p2p.toFixed(0)} µV)
                      </span>
                    </div>
                  ))}
                </div>
              )}
              <div style={S.btnRow}>
                <button style={S.btn} onClick={onExit}>
                  Exit
                </button>
                <button
                  style={S.btnPrimary}
                  onClick={() => {
                    setStep("intro");
                    setProgress(0);
                    setErrorMsg("");
                    setDetectedBlinks(0);
                    setSignalInfo([]);
                  }}
                >
                  Try Again
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// ═════════════════════════════════════════════════════════════════════════════
// Browse Mode
// ═════════════════════════════════════════════════════════════════════════════

interface BrowseModeProps {
  eegData: EEGData;
  calibration: BlinkCalibration;
  onRecalibrate: () => void;
  onExit: () => void;
}

function BrowseMode({
  eegData,
  calibration,
  onRecalibrate,
  onExit,
}: BrowseModeProps) {
  const [scrollDir, setScrollDir] = useState<"down" | "up">("down");
  const [blinkFlash, setBlinkFlash] = useState(false);
  const [enabled, setEnabled] = useState(true);
  const [scrollAmount, setScrollAmount] = useState(calibration.scrollAmount);
  const [amp, setAmp] = useState(0);
  const [blinkTotal, setBlinkTotal] = useState(0);
  const [mode, setMode] = useState<"reader" | "web">("reader");
  const [url, setUrl] = useState(
    "https://en.wikipedia.org/wiki/Electroencephalography",
  );
  const [iframeUrl, setIframeUrl] = useState("");
  const [iframeScroll, setIframeScroll] = useState(0);
  const [showSettings, setShowSettings] = useState(false);
  const [threshold, setThreshold] = useState(calibration.threshold);

  const contentRef = useRef<HTMLDivElement>(null);
  const stateRef = useRef<"idle" | "in-blink">("idle");
  const lastBlinkRef = useRef(0);
  const blinkStartRef = useRef(0);
  const flashTimeoutRef = useRef(0);
  const ampRef = useRef(0);
  const lastAmpUpdate = useRef(0);
  const doScrollRef = useRef<() => void>(() => {});

  // ── Scroll action ──
  const doScroll = useCallback(() => {
    setBlinkTotal((c) => c + 1);
    setBlinkFlash(true);
    clearTimeout(flashTimeoutRef.current);
    flashTimeoutRef.current = window.setTimeout(
      () => setBlinkFlash(false),
      200,
    );

    const amount = scrollDir === "down" ? scrollAmount : -scrollAmount;

    if (mode === "reader" && contentRef.current) {
      contentRef.current.scrollBy({ top: amount, behavior: "smooth" });
    } else if (mode === "web") {
      setIframeScroll((prev) => Math.max(0, prev + amount));
    }
  }, [scrollDir, scrollAmount, mode]);

  // Keep doScrollRef in sync so the RAF loop always calls the latest version
  doScrollRef.current = doScroll;

  // ── Blink detection loop (RAF) ──
  useEffect(() => {
    if (!enabled) return;

    const WINDOW = 25; // 100ms
    const REFRACTORY_MS = 400;
    const MAX_BLINK_MS = 600;
    const MIN_BLINK_MS = 30;
    const CHECK_MS = 20;

    let lastCheck = 0;
    let raf: number;

    function check() {
      const now = performance.now();
      if (now - lastCheck < CHECK_MS) {
        raf = requestAnimationFrame(check);
        return;
      }
      lastCheck = now;

      const a = readAmplitude(eegData, calibration.channels, WINDOW);
      ampRef.current = a;

      // Throttle React state update for amplitude display (every 80ms)
      if (now - lastAmpUpdate.current > 80) {
        lastAmpUpdate.current = now;
        setAmp(a);
      }

      const above = a > threshold;
      const state = stateRef.current;

      if (state === "idle") {
        if (above && now - lastBlinkRef.current > REFRACTORY_MS) {
          stateRef.current = "in-blink";
          blinkStartRef.current = now;
        }
      } else if (state === "in-blink") {
        if (!above) {
          const dur = now - blinkStartRef.current;
          if (dur >= MIN_BLINK_MS && dur <= MAX_BLINK_MS) {
            lastBlinkRef.current = now;
            stateRef.current = "idle";
            doScrollRef.current();
          } else {
            stateRef.current = "idle";
          }
        } else if (now - blinkStartRef.current > MAX_BLINK_MS) {
          stateRef.current = "idle";
        }
      }

      raf = requestAnimationFrame(check);
    }

    raf = requestAnimationFrame(check);
    return () => cancelAnimationFrame(raf);
  }, [enabled, eegData, calibration, threshold]);

  // ── Keyboard shortcuts ──
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement) return;
      switch (e.key) {
        case "Escape":
          if (showSettings) setShowSettings(false);
          else onExit();
          break;
        case " ":
          e.preventDefault();
          setScrollDir((d) => (d === "down" ? "up" : "down"));
          break;
        case "s":
        case "S":
          setShowSettings((v) => !v);
          break;
        case "+":
        case "=":
          setScrollAmount((v) => Math.min(800, v + 50));
          break;
        case "-":
        case "_":
          setScrollAmount((v) => Math.max(50, v - 50));
          break;
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onExit, showSettings]);

  // ── Amplitude meter ──
  const ampPct = Math.min(100, (amp / (threshold * 2)) * 100);
  const threshPct = Math.min(100, (threshold / (threshold * 2)) * 100);
  const meterColor = amp > threshold ? "#00c853" : "#333";

  return (
    <div style={S.root}>
      {/* ── Header ── */}
      <div style={S.header}>
        <button style={S.btnSmall} onClick={onExit}>
          ← Exit
        </button>
        <div style={S.headerTitle}>Blink Browser</div>

        {/* Amplitude meter */}
        <div style={S.meterWrap}>
          <div
            style={{
              ...S.meterFill,
              width: `${ampPct}%`,
              background: meterColor,
            }}
          />
          <div style={{ ...S.meterThreshLine, left: `${threshPct}%` }} />
        </div>

        {/* Blink indicator */}
        <div
          style={{
            ...S.blinkBadge,
            background: blinkFlash
              ? "rgba(0,200,83,0.2)"
              : "rgba(255,255,255,0.04)",
            color: blinkFlash ? "#00c853" : "#666",
            border: blinkFlash
              ? "1px solid rgba(0,200,83,0.3)"
              : "1px solid rgba(255,255,255,0.06)",
          }}
        >
          {blinkFlash ? "BLINK" : `${blinkTotal} blinks`}
        </div>

        {/* Direction toggle */}
        <button
          style={S.dirBtn}
          onClick={() =>
            setScrollDir((d) => (d === "down" ? "up" : "down"))
          }
          title="Toggle scroll direction (Space)"
        >
          {scrollDir === "down" ? "↓" : "↑"} {scrollDir}
        </button>

        {/* Enable toggle */}
        <button
          style={{
            ...S.btnSmall,
            background: enabled ? "rgba(0,200,83,0.1)" : "#111",
            color: enabled ? "#00c853" : "#666",
            borderColor: enabled
              ? "rgba(0,200,83,0.2)"
              : "rgba(255,255,255,0.1)",
          }}
          onClick={() => setEnabled((v) => !v)}
        >
          {enabled ? "● ON" : "○ OFF"}
        </button>

        {/* Settings */}
        <button
          style={S.btnSmall}
          onClick={() => setShowSettings((v) => !v)}
          title="Settings (S)"
        >
          ⚙
        </button>
      </div>

      {/* ── URL bar / mode tabs ── */}
      <div style={S.urlBar}>
        <button
          style={{
            ...S.modeTab,
            background:
              mode === "reader" ? "rgba(0,112,243,0.1)" : "transparent",
            color: mode === "reader" ? "#3291ff" : "#666",
            borderColor:
              mode === "reader"
                ? "rgba(0,112,243,0.2)"
                : "rgba(255,255,255,0.08)",
          }}
          onClick={() => setMode("reader")}
        >
          📖 Reader
        </button>
        <button
          style={{
            ...S.modeTab,
            background:
              mode === "web" ? "rgba(0,112,243,0.1)" : "transparent",
            color: mode === "web" ? "#3291ff" : "#666",
            borderColor:
              mode === "web"
                ? "rgba(0,112,243,0.2)"
                : "rgba(255,255,255,0.08)",
          }}
          onClick={() => setMode("web")}
        >
          🌐 Web
        </button>

        {mode === "web" && (
          <>
            <input
              style={S.urlInput}
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  let u = url.trim();
                  if (u && !u.startsWith("http")) u = "https://" + u;
                  setIframeUrl(u);
                  setIframeScroll(0);
                }
              }}
              placeholder="Enter URL and press Enter…"
              spellCheck={false}
            />
            <button
              style={S.btnSmall}
              onClick={() => {
                let u = url.trim();
                if (u && !u.startsWith("http")) u = "https://" + u;
                setIframeUrl(u);
                setIframeScroll(0);
              }}
            >
              Go
            </button>
          </>
        )}
      </div>

      {/* ── Content area ── */}
      {mode === "reader" ? (
        <div ref={contentRef} style={S.content}>
          {ARTICLES.map((art, i) => (
            <div key={i}>
              {i > 0 && <hr style={S.articleDivider} />}
              <article style={S.article}>
                <h1 style={S.articleTitle}>{art.title}</h1>
                <div style={S.articleBody}>{art.body}</div>
              </article>
            </div>
          ))}
          <div
            style={{
              textAlign: "center",
              padding: "60px 0",
              color: "#444",
              fontSize: 14,
            }}
          >
            — End of articles —
          </div>
        </div>
      ) : (
        <div style={S.iframeWrap}>
          {iframeUrl ? (
            <iframe
              src={iframeUrl}
              title="Blink Browser"
              sandbox="allow-scripts allow-same-origin allow-forms"
              referrerPolicy="no-referrer"
              style={{
                ...S.iframe,
                transform: `translateY(${-iframeScroll}px)`,
              }}
            />
          ) : (
            <div
              style={{
                flex: 1,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: "#444",
                fontSize: 14,
              }}
            >
              Enter a URL above and press Enter or Go.
              <br />
              Note: some websites block iframe embedding.
            </div>
          )}
        </div>
      )}

      {/* ── Settings panel ── */}
      {showSettings && (
        <div style={S.settingsPanel}>
          <div>
            <div style={S.settLabel}>Scroll amount</div>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <button
                style={S.btnSmall}
                onClick={() => setScrollAmount((v) => Math.max(50, v - 50))}
              >
                −
              </button>
              <span style={S.settValue}>{scrollAmount}px</span>
              <button
                style={S.btnSmall}
                onClick={() => setScrollAmount((v) => Math.min(800, v + 50))}
              >
                +
              </button>
            </div>
          </div>
          <div>
            <div style={S.settLabel}>Threshold</div>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <button
                style={S.btnSmall}
                onClick={() => setThreshold((v) => Math.max(20, v - 10))}
              >
                −
              </button>
              <span style={S.settValue}>{threshold.toFixed(0)} µV</span>
              <button
                style={S.btnSmall}
                onClick={() => setThreshold((v) => Math.min(500, v + 10))}
              >
                +
              </button>
            </div>
          </div>
          <div>
            <div style={S.settLabel}>Channels</div>
            <span style={S.settValue}>
              {calibration.channels.map((c) => `Ch${c}`).join(", ")}
            </span>
          </div>
          <div>
            <div style={S.settLabel}>Calibrated</div>
            <span style={{ ...S.settValue, fontSize: 12 }}>
              {new Date(calibration.timestamp).toLocaleString()}
            </span>
          </div>
          <button style={S.btnSmall} onClick={onRecalibrate}>
            🔄 Recalibrate
          </button>
          <div style={{ flex: 1 }} />
          <button
            style={S.btnSmall}
            onClick={() => setShowSettings(false)}
          >
            Close (S)
          </button>
        </div>
      )}

      {/* ── Footer ── */}
      <div style={S.footer}>
        <span>
          <strong>Space</strong> toggle direction
        </span>
        <span>
          <strong>+/−</strong> scroll amount
        </span>
        <span>
          <strong>S</strong> settings
        </span>
        <span>
          <strong>Esc</strong> exit
        </span>
        <div style={{ flex: 1 }} />
        <span style={{ fontFamily: "'Geist Mono',monospace" }}>
          {amp.toFixed(0)} µV
        </span>
      </div>
    </div>
  );
}

// ═════════════════════════════════════════════════════════════════════════════
// Main Experience Component
// ═════════════════════════════════════════════════════════════════════════════

interface Props {
  eegData: EEGData;
  yScale: number;
  onExit: () => void;
}

export default function BlinkBrowser({ eegData, yScale, onExit }: Props) {
  const [calibration, setCalibration] = useState<BlinkCalibration | null>(
    () => loadCalibration(),
  );
  const [showCal, setShowCal] = useState(!loadCalibration());

  if (showCal) {
    return (
      <CalibrationWizard
        eegData={eegData}
        existing={calibration}
        onComplete={(cal) => {
          saveCalibration(cal);
          setCalibration(cal);
          setShowCal(false);
        }}
        onSkip={calibration ? () => setShowCal(false) : undefined}
        onExit={onExit}
      />
    );
  }

  return (
    <BrowseMode
      eegData={eegData}
      calibration={calibration!}
      onRecalibrate={() => setShowCal(true)}
      onExit={onExit}
    />
  );
}
